version: '3'
services: 
    web:
      image: notes-nodejs
      build: .
      command: "node src/index.js"
      ports: 
        - "4000:4000"
      depends_on: 
        - "mongo"
    mongo:
        image: "mongo"
        ports: 
            - "27017:27017"